# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\x1a\x1bgoogle/protobuf/empty.proto\",\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1e\n\x0bTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\",\n\x0cTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\"1\n\x10TermListResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\".\n\x0e\x41\x64\x64TermRequest\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\"1\n\x11UpdateTermRequest\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t2\xd1\x02\n\x0fGlossaryService\x12\x41\n\x0bGetAllTerms\x12\x16.google.protobuf.Empty\x1a\x1a.glossary.TermListResponse\x12\x38\n\x07GetTerm\x12\x15.glossary.TermRequest\x1a\x16.glossary.TermResponse\x12;\n\x07\x41\x64\x64Term\x12\x18.glossary.AddTermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=57
  _globals['_TERM']._serialized_end=101
  _globals['_TERMREQUEST']._serialized_start=103
  _globals['_TERMREQUEST']._serialized_end=133
  _globals['_TERMRESPONSE']._serialized_start=135
  _globals['_TERMRESPONSE']._serialized_end=179
  _globals['_TERMLISTRESPONSE']._serialized_start=181
  _globals['_TERMLISTRESPONSE']._serialized_end=230
  _globals['_ADDTERMREQUEST']._serialized_start=232
  _globals['_ADDTERMREQUEST']._serialized_end=278
  _globals['_UPDATETERMREQUEST']._serialized_start=280
  _globals['_UPDATETERMREQUEST']._serialized_end=329
  _globals['_DELETETERMREQUEST']._serialized_start=331
  _globals['_DELETETERMREQUEST']._serialized_end=367
  _globals['_GLOSSARYSERVICE']._serialized_start=370
  _globals['_GLOSSARYSERVICE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
